employeename=input("Enter the employee name :\n")
employeesalary=float(input("Enter the employee salary :\n"))
employeePhone=int(input("Enter the employee Phone :\t"))
employeeAddress=str(input("Enter the employee Address :\t"))
print(employeename,type(employeename))
print(employeesalary,type(employeesalary))
print(employeePhone,type(employeePhone))
print(employeeAddress,type(employeeAddress))