mynum=[1,2,3,4,8,7,6,5,11,32,15,6]
# mynum.sort()
# print(mynum)
# mynum.append(100)
# print(mynum)
# print(mynum.index(100))
# mynum2=mynum.copy()
# print(mynum2)
mynum.insert(8,9)
print(mynum)
# mynum.pop()
# mynum.pop()
# mynum.pop()
# print(mynum)
print(mynum.count(6))

mynum.reverse()
print(mynum)